server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: booking-service
          uri: lb://BOOKING-SERVICE
          predicates:
            - Path=/booking/**
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**
