server:
  port: 0

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/hoteldb
    username: root
    password: 123456

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
