server:
  port: 0

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/userdb
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
